import {DIFFICULTIES} from './data.js';import {storage,publish} from './storage.js';
const rank=id=>DIFFICULTIES.find(d=>d.id===id)?.rank??1;
const cleanChoice=s=>String(s??'').replace(/^[^A-Za-zÀ-ÿ0-9]+/,'').trim();
export function resolveStep(step,difficulty='aventure'){
  let out={...step,...(step.variants?.[difficulty]||{})};
  const r=rank(difficulty),diff=DIFFICULTIES.find(d=>d.id===difficulty)||DIFFICULTIES[1];
  if(!step.variants?.[difficulty]&&r>=2&&out.type==='choice'&&Array.isArray(out.options)){
    const correct=out.options[Number(out.answer)];
    out={...out,type:'text',answer:[String(correct),cleanChoice(correct)],prompt:out.prompt+' Répondez sans propositions.'};delete out.options;
  }
  if(out.type==='memory'){
    out.memoryMs=diff.memoryMs;
    if(difficulty==='decouverte'&&Array.isArray(out.sequence)&&out.sequence.length>3){out.sequence=out.sequence.slice(0,3);out.answer=out.sequence.slice();}
  }
  out.level=difficulty;return out
}
export function activeSteps(scenario,difficulty='aventure'){const r=rank(difficulty);return scenario.steps.filter(s=>(s.minRank??0)<=r&&(s.maxRank??99)>=r).map(s=>resolveStep(s,difficulty));}
export function initialProgress(session,team,scenario){return {sessionId:session.id,teamId:team.id,scenarioId:scenario.id,stepIndex:0,worldIndex:0,score:0,hintsUsed:0,hintCost:0,attempts:0,inventory:[],completedSteps:[],startedAt:session.startedAt||null,finishedAt:null,lastSeen:Date.now(),answers:{},events:[],bonusTimeMs:0,hostMessage:null,introSeen:false,seenChapters:[],currentStepId:null,currentStepStartedAt:null}}
export function loadProgress(s,t){return storage.get(`progress:${s}:${t}`)}export function saveProgress(p){p.lastSeen=Date.now();storage.set(`progress:${p.sessionId}:${p.teamId}`,p);publish('progress',{sessionId:p.sessionId,teamId:p.teamId,stepIndex:p.stepIndex,worldIndex:p.worldIndex,score:p.score,finishedAt:p.finishedAt});return p}
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase().replace(/\s+/g,' ');const seteq=(a,b)=>a.length===b.length&&[...a].sort().every((v,i)=>v===[...b].sort()[i]);
export function validateAnswer(step,value){if(step.type==='choice')return Number(value)===Number(step.answer);if(['text','team_split','keypad','cipher','reveal','hotspot'].includes(step.type)){const a=Array.isArray(step.answer)?step.answer:[step.answer];return a.some(x=>norm(x)===norm(value))}if(step.type==='multi'||step.type==='file_hunt'||step.type==='color_code'||step.type==='memory')return seteq(value||[],step.answer||[])&&(['color_code','memory'].includes(step.type)?JSON.stringify(value)===JSON.stringify(step.answer):true);if(step.type==='order')return JSON.stringify(value||[])===JSON.stringify(step.answer||[]);if(step.type==='lock_parts'){const a=value||[],b=step.answer||[];return a.length===b.length&&a.every((x,i)=>norm(x)===norm(b[i]))}if(step.type==='match')return value==='ok'||value===true;if(step.type==='physical'){if(step.hostValidation&&value===true)return true;const accepted=(Array.isArray(step.answer)?step.answer:[step.answer]).filter(Boolean).map(norm);return accepted.includes(norm(value))}if(step.type==='sound')return norm(value)===norm(step.answer);return false}
export function submitAnswer({progress,step,value,difficultyId='aventure'}){const ok=validateAnswer(step,value),diff=DIFFICULTIES.find(d=>d.id===difficultyId)||DIFFICULTIES[1];progress.attempts++;progress.answers[step.id]=value;progress.events.push({type:'answer',stepId:step.id,ok,at:Date.now()});if(ok){const earned=Math.max(10,Math.round((step.points||100)*diff.scoreMultiplier));progress.score+=earned;if(step.reward&&!progress.inventory.some(x=>x.id===step.reward.id))progress.inventory.push(step.reward);if(!progress.completedSteps.includes(step.id))progress.completedSteps.push(step.id);progress.stepIndex++;progress.currentStepId=null;progress.currentStepStartedAt=null}else progress.score=Math.max(0,progress.score-(diff.attemptPenalty||0));saveProgress(progress);return {ok,progress}}
export function hintText(step,kind){const h=step.hints||[];if(kind==='clue')return h[0]||'Relisez la consigne et répartissez les informations entre les joueurs.';if(kind==='strong'){const map={choice:'Éliminez d’abord les réponses incompatibles avec les faits.',text:'Cherchez le mot ou nombre commun aux indices déjà trouvés.',keypad:'Reprenez chaque contrainte une par une avant de former le code.',order:'Identifiez d’abord le premier et le dernier élément.',multi:'Écartez les choix qui contredisent directement le dossier.',team_split:'Aucun joueur ne possède tout : faites lire chaque carte à voix haute.',reveal:'Utilisez les boutons de révélation dans l’ordre.',hotspot:'Fouillez méthodiquement chaque zone sans cliquer au hasard.',file_hunt:'Repérez le chemin, le nom du fichier et ce qui est réellement utile.',lock_parts:'Chaque case du verrou correspond à une information différente.',memory:'Regroupez la séquence en deux petits blocs.',sound:'Comparez les sons deux par deux.',match:'Cherchez les couples les plus évidents avant les autres.',physical:'Vérifiez le matériel préparé et la zone indiquée par l’animateur.'};return map[step.type]||'Recoupez deux indices différents avant de répondre.'}if(kind==='solution'){if(h[1])return h[1];const a=Array.isArray(step.answer)?step.answer.join(' → '):step.answer;return `Solution : ${a}`;}return null}
export function useHint(progress,step,kind='clue'){const cost=kind==='clue'?1:kind==='strong'?2:3,content=hintText(step,kind);progress.hintsUsed++;progress.hintCost=(progress.hintCost||0)+cost;progress.score=Math.max(0,progress.score-(kind==='clue'?10:kind==='strong'?25:50));progress.events.push({type:'hint',kind,stepId:step.id,cost,at:Date.now()});saveProgress(progress);return content}
export function ensureStepClock(progress,step){if(progress.currentStepId!==step.id){progress.currentStepId=step.id;progress.currentStepStartedAt=Date.now();saveProgress(progress)}return progress}
export function solutionAvailable(progress,difficultyId){const d=DIFFICULTIES.find(x=>x.id===difficultyId)||DIFFICULTIES[1];return !d.solutionDelaySec||!progress.currentStepStartedAt||(Date.now()-progress.currentStepStartedAt)>=d.solutionDelaySec*1000}
export function solutionWait(progress,difficultyId){const d=DIFFICULTIES.find(x=>x.id===difficultyId)||DIFFICULTIES[1],left=Math.max(0,d.solutionDelaySec*1000-(Date.now()-(progress.currentStepStartedAt||Date.now())));return Math.ceil(left/1000)}
export function finish(p){p.finishedAt=Date.now();return saveProgress(p)}export function elapsedMs(p){if(!p.startedAt)return 0;return Math.max(0,(p.finishedAt||Date.now())-p.startedAt)}
export function derivedWorldCode(world,team){return `${String(world.code).replace(/\s+/g,'')}${team?.teamKey||'01'}`.toUpperCase()}
export function validateWorldCode(world,team,value){return norm(derivedWorldCode(world,team)).replace(/ /g,'')===norm(value).replace(/ /g,'')}
export function currentWorldIndex(session,team,progress,worldCount){if(!worldCount)return 0;const start=session.rotationMode===false?0:(team.startWorldIndex||0);return (start+(progress.worldIndex||0))%worldCount}
