import {DIFFICULTIES} from './data.js';import {storage,publish} from './storage.js';
const rank=id=>DIFFICULTIES.find(d=>d.id===id)?.rank??1;export function activeSteps(scenario,difficulty='aventure'){const r=rank(difficulty);return scenario.steps.filter(s=>(s.minRank??0)<=r&&(s.maxRank??99)>=r).map(s=>resolveStep(s,difficulty));}
export function resolveStep(step,difficulty){return {...step,...(step.variants?.[difficulty]||{})}}
export function initialProgress(session,team,scenario){return {sessionId:session.id,teamId:team.id,scenarioId:scenario.id,stepIndex:0,worldIndex:0,score:0,hintsUsed:0,attempts:0,inventory:[],completedSteps:[],startedAt:session.startedAt||null,finishedAt:null,lastSeen:Date.now(),answers:{},events:[],bonusTimeMs:0,hostMessage:null}}
export function loadProgress(s,t){return storage.get(`progress:${s}:${t}`)}export function saveProgress(p){p.lastSeen=Date.now();storage.set(`progress:${p.sessionId}:${p.teamId}`,p);publish('progress',{sessionId:p.sessionId,teamId:p.teamId,stepIndex:p.stepIndex,worldIndex:p.worldIndex,score:p.score,finishedAt:p.finishedAt});return p}
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase().replace(/\s+/g,' ');const seteq=(a,b)=>a.length===b.length&&[...a].sort().every((v,i)=>v===[...b].sort()[i]);
export function validateAnswer(step,value){if(step.type==='choice')return Number(value)===Number(step.answer);if(['text','team_split','keypad','cipher'].includes(step.type)){const a=Array.isArray(step.answer)?step.answer:[step.answer];return a.some(x=>norm(x)===norm(value))}if(step.type==='multi'||step.type==='color_code'||step.type==='memory')return seteq(value||[],step.answer||[])&&(['color_code','memory'].includes(step.type)?JSON.stringify(value)===JSON.stringify(step.answer):true);if(step.type==='order')return JSON.stringify(value||[])===JSON.stringify(step.answer||[]);if(step.type==='match')return value==='ok'||value===true;if(step.type==='physical'){if(value===true)return true;const accepted=[...(Array.isArray(step.answer)?step.answer:[step.answer]),'VALIDE','OK'].map(norm);return accepted.includes(norm(value))}if(step.type==='sound')return norm(value)===norm(step.answer);return false}
export function submitAnswer({progress,step,value,difficultyId='aventure'}){const ok=validateAnswer(step,value),diff=DIFFICULTIES.find(d=>d.id===difficultyId)||DIFFICULTIES[1];progress.attempts++;progress.answers[step.id]=value;progress.events.push({type:'answer',stepId:step.id,ok,at:Date.now()});if(ok){const earned=Math.max(10,Math.round((step.points||100)*diff.scoreMultiplier));progress.score+=earned;if(step.reward&&!progress.inventory.some(x=>x.id===step.reward.id))progress.inventory.push(step.reward);if(!progress.completedSteps.includes(step.id))progress.completedSteps.push(step.id);progress.stepIndex++}else progress.score=Math.max(0,progress.score-(diff.attemptPenalty||0));saveProgress(progress);return {ok,progress}}
export function useHint(progress,step,index){if(!step.hints?.[index])return null;progress.hintsUsed++;progress.score=Math.max(0,progress.score-(index===0?15:30));progress.events.push({type:'hint',stepId:step.id,index,at:Date.now()});saveProgress(progress);return step.hints[index]}
export function finish(p){p.finishedAt=Date.now();return saveProgress(p)}export function elapsedMs(p){if(!p.startedAt)return 0;return Math.max(0,(p.finishedAt||Date.now())-p.startedAt)}
export function validateWorldCode(world,value){return norm(world.code).replace(/ /g,'')===norm(value).replace(/ /g,'')}
